---
default_stages: [pre-commit]

default_install_hook_types: [pre-commit, commit-msg]

ci:
  autoupdate_commit_msg: 'pre-commit: autoupdate hooks'
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/talos-systems/conform
    rev: v0.1.0-alpha.31
    hooks:
      - id: conform
        stages:
          - commit-msg

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.49.1
    hooks:
      - id: markdownlint
      - id: markdownlint-fix

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/MarketSquare/robotframework-robocop
    rev: v8.4.1
    hooks:
      - id: robocop
        additional_dependencies:
          - typing_extensions
      - id: robocop-format
        additional_dependencies:
          - typing_extensions

  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.65
    hooks:
      - id: ty
        args: [--isolated, --group, test, --project, osfv_cli]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.4
    hooks:
      - id: check-jsonschema
        args: [
          "--verbose",
          "--schemafile",
          "osfv_cli/src/osfv/models/schema/model_schema.yml",
        ]
        files: ^osfv_cli/src/osfv/models/.*\.yml$
        # Validate models not the schema itself.
        exclude: ^osfv_cli/src/osfv/models/schema/.*$

  - repo: local
    hooks:
      - id: check-osfv-models
        name: Validate all OSFV YAML models
        # Use bash to expand glob
        entry: bash -c 'check-jsonschema osfv_cli/src/osfv/models/*yml "$@"'
        args: [
          "--verbose",
          "--schemafile",
          "osfv_cli/src/osfv/models/schema/model_schema.yml"
        ]
        language: python
        additional_dependencies:
          - check-jsonschema
        # Run only if schema changed. 'check-jsonschema' verifies singular
        # model changes.
        files: ^osfv_cli/src/osfv/models/schema/.*\.yml$
        pass_filenames: false

  - repo: https://github.com/koxudaxi/datamodel-code-generator
    # Keep in sync with pyproject.toml otherwise manually generated model might
    # differ
    rev: 0.71.0
    hooks:
      - id: datamodel-code-generator
        entry: "bash -c 'cd osfv_cli && datamodel-codegen'"
        files: |
          (?x)^(
            osfv_cli/src/osfv/models/schema/.*\.yaml|
            osfv_cli/src/osfv/libs/models_gen.py
          )$
