[tool.robocop.lint]
ignore = [
    # TODO: add missing documentation for keywords and re-enable
    "DOC01",
    # TODO: add missing documentation for test cases and re-enable
    "DOC02",
    # TODO: add missing documentation for test suitdes and re-enable
    "DOC03",
    # TODO: consider re-enabling
    "NAME01",
    # TODO: consider fixing and re-enabling
    "VAR08",
    # TODO: fix and re-enable
    "DEPR05",
    # TODO: fix and re-enable
    "DEPR06",
    # TODO: fix and re-enable
    "COM01",
    "MISC06",
    # TODO: fix unused variables and re-enable
    "VAR02",
    # TODO: consider fixing and re-enabling
    "VAR03",
    # TODO: fix and re-enable
    "MISC13",
]
configure = [
    # TODO: consider reducing to default 40, or less
    "LEN01.max_len=50",
    # TODO: consider reducing to default 10, or less
    "LEN03.max_calls=50",
    # TODO: consider reducing to dfeault 20, or less
    "LEN04.max_len=50",
    # TODO: consider reducing to dfeault 10, or less
    "LEN06.max_calls=50",
    # TODO: reduce to default 400 or so
    "LEN28.max_lines=5000",
    # TODO: reduce to 120/80
    "LEN08.line_length=180",
]
