# generated by datamodel-codegen:
#   filename:  model_schema.yml

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class Voltage(StrEnum):
    """
    Chip supply voltage, as found in the appropriate datasheet.
    Most commonly "3.3V" or "1.8V".
    """

    field_3_3V = "3.3V"
    field_1_8V = "1.8V"


class LayoutItem(BaseModel):
    """
    Layout entry describing a name and its range.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    """
    Name of the layout entry.
    """
    range: str
    """
    Range associated with this layout entry.
    """


class FlashChip(BaseModel):
    """
    Details about the SPI flash chip on the platform.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    model: str = ""
    """
    Flash chip model, corresponding to the `-c` parameter used in
    flashrom. Optional, but must be set if flashrom detects more than
    one possible flash chip model.
    """
    voltage: Voltage
    """
    Chip supply voltage, as found in the appropriate datasheet.
    Most commonly "3.3V" or "1.8V".
    """
    layout: list[LayoutItem] = Field([], validate_default=True)
    """
    Layout entries, each identifying a name and its range.
    """


class Name(StrEnum):
    """
    Name of the programmer connected to the platform.
    """

    rte_1_0 = "rte_1_0"
    rte_1_1 = "rte_1_1"
    ch341a = "ch341a"
    dediprog = "dediprog"


class Programmer(BaseModel):
    """
    The programmer connected to the platform.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: Name
    """
    Name of the programmer connected to the platform.
    """


class FlashingPowerState(StrEnum):
    """
    The power state the platform needs to be in for SPI flashing.
    """

    S5 = "S5"
    G3 = "G3"


class PwrCtrl(BaseModel):
    """
    Power control configuration for flashing.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    sonoff: bool
    """
    Whether Sonoff power control is used.
    """
    relay: bool
    """
    Whether onboard RTE relay power control is used.
    """
    flashing_power_state: FlashingPowerState
    """
    The power state the platform needs to be in for SPI flashing.
    """
    discharge_psu: bool = True
    """
    Whether to discharge PSU after powering it off.
    """


class Polarity(StrEnum):
    """
    Power LED GPIO polarity. 'active low' means platform is ON
    if GPIO is low.
    """

    active_low = "active low"
    active_high = "active high"


class PwrLed(BaseModel):
    """
    Power LED configuration
    """

    polarity: Polarity
    """
    Power LED GPIO polarity. 'active low' means platform is ON
    if GPIO is low.
    """


class FlashingConfiguration(BaseModel):
    """
    Schema describing platform flashing configuration, including flash chip
    identification, programmer selection, power control settings, and optional
    post/pre-flash operations.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    flash_chip: FlashChip
    """
    Details about the SPI flash chip on the platform.
    """
    programmer: Programmer
    """
    The programmer connected to the platform.
    """
    pwr_ctrl: PwrCtrl
    """
    Power control configuration for flashing.
    """
    pwr_led: PwrLed = Field({"polarity": "active high"}, validate_default=True)
    """
    Power LED configuration
    """
    reset_cmos: bool = False
    """
    Whether a CMOS reset is required after flashing. Optional; defaults
    to false.
    """
    disable_wp: bool = False
    """
    Whether flash write-protect (WP) needs to be disabled before
    flashing. Optional; defaults to false.
    """
